drop schema if exists PIRATEX;
CREATE SCHEMA IF NOT EXISTS PIRATEX;
USE PIRATEX;

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT AUTO_INCREMENT ,
    NM_CATEGORIA VARCHAR(50) NOT NULL,
    PRIMARY key( ID_CATEGORIA)
);
CREATE TABLE SERIE (
	ID_SERIE 			INT NOT NULL AUTO_INCREMENT,
	NM_SERIE 			VARCHAR(45)  NOT NULL,
	NM_ORIGINAL_SERIE 	VARCHAR(45)      NULL,
	AA_SERIE 			VARCHAR(45)  NOT NULL,
	QT_TEMPORADAS 		INT UNSIGNED NOT NULL,
	QT_EPISODIOS 		INT UNSIGNED NOT NULL,
	DS_SINOPSE_SERIE 	TEXT		     NULL,
	PRIMARY KEY (ID_SERIE)
);

CREATE TABLE EPISODIO(
	ID_SERIE 	INT NOT NULL,
	ID_TEMPORADA INT NOT NULL,
	ID_EPISODIO DECIMAL(4,2) NOT NULL,
	NM_EPISODIO VARCHAR(60) NOT NULL,
	NM_ORIGINAL_EPISODIO VARCHAR(60) NULL,
	DT_EXIBICAO DATE NULL,
	QT_DURACAO 	INT NOT NULL,
	DS_EPISODIO TEXT NULL,
	DS_OBSERVACAO_EPISODIO TEXT NULL,
	PRIMARY KEY (ID_TEMPORADA, ID_SERIE, ID_EPISODIO),
    FOREIGN KEY (ID_SERIE) REFERENCES SERIE(ID_SERIE)
);
CREATE TABLE SERIE_CATEGORIA(
  ID_SERIE 	   INT NOT NULL,
  ID_CATEGORIA INT NOT NULL,
  PRIMARY KEY (ID_CATEGORIA, ID_SERIE),
  FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
  FOREIGN KEY (ID_SERIE	   ) REFERENCES SERIE(ID_SERIE)
); 